### ISSUE TITLE
Unable to get model output

### ISSUE THREAD

**Issue by AnandSingh-0619** [AnandSingh-0619/habitat-lab#1]
## Habitat-Lab and Habitat-Sim versions
Habitat-Lab: vx.x.x or master?

Habitat-Sim: vx.x.x or master?

Habitat is under active development, and we advise users to restrict themselves to stable releases. Are you using the latest release versions of [Habitat-Lab](https://github.com/facebookresearch/habitat-lab/releases) and [Habitat-Sim](https://github.com/facebookresearch/habitat-sim/releases)? Your question may already be addressed in the latest versions. We may also not be able to help with problems in earlier versions because they sometimes lack the more verbose logging needed for debugging.

Master branch contains 'bleeding edge' code and should be used at your own risk.

## Docs and Tutorials
Did you read the docs? https://aihabitat.org/docs/habitat-lab/

Did you check out the tutorials? https://aihabitat.org/tutorial/2020/

Perhaps your question is answered there. If not, carry on!

## ❓ Questions and Help
I have loaded the weights of the model and it gives no error. 
Unable to pass input to the [model``](https://github.com/AnandSingh-0619/habitat-lab/blob/anand_dev/examples/tutorials/Task2.ipynb?short_path=12800c8#L458C1-L463C42)
@yusufali98

**Comment by yusufali98** [comment]
i think this was an issue with the observation tensor shapes but was resolved
